name: Deploy

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    uses: ./.github/workflows/rust.yml

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install musl-tools
      run: sudo apt install musl-tools
    - name: Install musl rust
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build release
      run: cargo build --release --target x86_64-unknown-linux-musl
    - name: Show hash
      run: sha1sum target/x86_64-unknown-linux-musl/release/thing-lists
    - name: Show executable size
      run: ls -lh target/x86_64-unknown-linux-musl/release/thing-lists

    - name: Setup SSH Keys
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
    - name: Copy executable
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          scp -o StrictHostKeyChecking=no target/x86_64-unknown-linux-musl/release/thing-lists droundy@lists.for-our.info:thing-lists.new
    - name: Rename executable
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          ssh -v -o StrictHostKeyChecking=no -l droundy lists.for-our.info mv -v thing-lists.new thing-lists
    - name: ls -lh
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          ssh -v -o StrictHostKeyChecking=no -l droundy lists.for-our.info ls -lh thing-lists

