name: Deploy

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    uses: ./.github/workflows/rust.yml

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install musl-tools
      run: sudo apt install musl-tools
    - name: Install musl rust
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build release
      run: cargo build --release --target x86_64-unknown-linux-musl
    - name: Show hash
      run: sha1sum target/x86_64-unknown-linux-musl/release/thing-lists
    - name: Show executable size
      run: ls -lh target/x86_64-unknown-linux-musl/release/thing-lists
    - name: Store release binary
      uses: actions/upload-artifact@v3
      with:
        name: binary
        path: target/x86_64-unknown-linux-musl/release/thing-lists

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Grab the binary
      uses: actions/download-artifact@v3
      with:
        name: binary
    - name: Show hash
      run: sha1sum target/x86_64-unknown-linux-musl/release/thing-lists

    - name: Setup SSH Keys and known_hosts
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

    - name: Test that we can ssh
      env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: ssh lists.for-our.info date

